// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SICOBIM_B.Data;

namespace SICOBIM_B.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201109022137_jzlz_33")]
    partial class jzlz_33
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SICOBIM_B.Entities.CatArea", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("area")
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idusuarioMod")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioAlta")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatArea");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatEstadoDelBien", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatEstadoDelBien");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatEstatus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("estatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatEstatus");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatGarantia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("añosGarantia")
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatGarantia");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatPermiso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("permiso")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatPermiso");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatPisos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("piso")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatPiso");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatRol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("idusuarioMod")
                        .HasColumnType("integer");

                    b.Property<string>("rol")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("CatRol");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatServicio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idusuarioMod")
                        .HasColumnType("integer");

                    b.Property<string>("servicio")
                        .HasColumnType("text");

                    b.Property<int>("usuarioAlta")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatServicio");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatSexo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("sexo")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatSexo");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoContrato", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("contrato")
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatTipoContrato");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoDeBien", b =>
                {
                    b.Property<int>("CatTipoDeBienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("TipodeBien")
                        .HasColumnType("text");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("CatTipoDeBienId");

                    b.ToTable("CatTipoDeBien");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoEntrada", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("tipoentrada")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatTipoEntrada");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoPartida", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("partidapresupestual")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatTipoPartida");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoSalida", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("tiposalida")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatTipoSalida");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTurno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("turno")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatTurno");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatUnidadDestino", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("destino")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("idusuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatUnidadDestino");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblAreaServicio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("catareaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catservicioid")
                        .HasColumnType("integer");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("catareaid");

                    b.HasIndex("catservicioid");

                    b.ToTable("TblAreaServicio");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("IProveedorid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdAreaServicioid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdClaveCabmsid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdClaveSaicaid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdContratoBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFacturasTblFacturasId")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFederalizacionid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdInventariosid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdResguardatariosid")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("catEstadoDelBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("catGarantiaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catPisosid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoDeBienesCatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoEntradaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoPartidaid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("serie")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("IProveedorid");

                    b.HasIndex("IdAreaServicioid");

                    b.HasIndex("IdClaveCabmsid");

                    b.HasIndex("IdClaveSaicaid");

                    b.HasIndex("IdContratoBienid");

                    b.HasIndex("IdFacturasTblFacturasId");

                    b.HasIndex("IdFederalizacionid");

                    b.HasIndex("IdInventariosid");

                    b.HasIndex("IdResguardatariosid");

                    b.HasIndex("catEstadoDelBienid");

                    b.HasIndex("catGarantiaid");

                    b.HasIndex("catPisosid");

                    b.HasIndex("catTipoDeBienesCatTipoDeBienId");

                    b.HasIndex("catTipoEntradaid");

                    b.HasIndex("catTipoPartidaid");

                    b.ToTable("TblBienesMuebles");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienesEquMedico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("IdAreaServicioid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdClaveCabmsid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdClaveSaicaid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdContratoBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFederalizacionid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdInventarioid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProveedorid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdResguardatariosid")
                        .HasColumnType("integer");

                    b.Property<int>("TblFacturasId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("catEstadoDelBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("catGarantiaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catPisosid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoDeBienesCatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoEntradaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoPartidaid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("serie")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("IdAreaServicioid");

                    b.HasIndex("IdClaveCabmsid");

                    b.HasIndex("IdClaveSaicaid");

                    b.HasIndex("IdContratoBienid");

                    b.HasIndex("IdFederalizacionid");

                    b.HasIndex("IdInventarioid");

                    b.HasIndex("IdProveedorid");

                    b.HasIndex("IdResguardatariosid");

                    b.HasIndex("TblFacturasId");

                    b.HasIndex("catEstadoDelBienid");

                    b.HasIndex("catGarantiaid");

                    b.HasIndex("catPisosid");

                    b.HasIndex("catTipoDeBienesCatTipoDeBienId");

                    b.HasIndex("catTipoEntradaid");

                    b.HasIndex("catTipoPartidaid");

                    b.ToTable("TblBienesEquMedico");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienesSistemas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("IdAreaServicioid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdClaveCabmsid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdClaveSaicaid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdContratoBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFacturasTblFacturasId")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFederalizacionid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdInventariosid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProveedorid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdResguardatariosid")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("catEstadoDelBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("catGarantiaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catPisosid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoDeBienesCatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoEntradaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoPartidaid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("serie")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("IdAreaServicioid");

                    b.HasIndex("IdClaveCabmsid");

                    b.HasIndex("IdClaveSaicaid");

                    b.HasIndex("IdContratoBienid");

                    b.HasIndex("IdFacturasTblFacturasId");

                    b.HasIndex("IdFederalizacionid");

                    b.HasIndex("IdInventariosid");

                    b.HasIndex("IdProveedorid");

                    b.HasIndex("IdResguardatariosid");

                    b.HasIndex("catEstadoDelBienid");

                    b.HasIndex("catGarantiaid");

                    b.HasIndex("catPisosid");

                    b.HasIndex("catTipoDeBienesCatTipoDeBienId");

                    b.HasIndex("catTipoEntradaid");

                    b.HasIndex("catTipoPartidaid");

                    b.ToTable("TblBienesSistemas");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblClaveCabms", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("clavecambs")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblClaveCambs");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblClaveSaica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("clavesaica")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblClaveSaica");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblConfPerfil", b =>
                {
                    b.Property<int?>("IdPermisoid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdRolid")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasIndex("IdPermisoid");

                    b.HasIndex("IdRolid");

                    b.ToTable("TblConfPerfil");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblContratoBien", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("contratobien")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblContratoBien");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblFacturas", b =>
                {
                    b.Property<int>("TblFacturasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<double>("IVA")
                        .HasColumnType("double precision");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<double>("costoTotal")
                        .HasColumnType("double precision");

                    b.Property<string>("factura")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<double>("subtotal")
                        .HasColumnType("double precision");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblFacturasId");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblFacturas");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblFederalizacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("federalizacion")
                        .HasColumnType("text");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblFederalizacion");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblInstrumentalMedico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("IdAreaServicioid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdClaveCambsid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdClaveSaicaid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdContratoBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFacturasTblFacturasId")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFederalizacionid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdInventariosid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProveedorid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdResguardatariosid")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("catEstadoDelBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("catGarantiaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catPisosid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoDeBienesCatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoEntradaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoPartidaid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("serie")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("IdAreaServicioid");

                    b.HasIndex("IdClaveCambsid");

                    b.HasIndex("IdClaveSaicaid");

                    b.HasIndex("IdContratoBienid");

                    b.HasIndex("IdFacturasTblFacturasId");

                    b.HasIndex("IdFederalizacionid");

                    b.HasIndex("IdInventariosid");

                    b.HasIndex("IdProveedorid");

                    b.HasIndex("IdResguardatariosid");

                    b.HasIndex("catEstadoDelBienid");

                    b.HasIndex("catGarantiaid");

                    b.HasIndex("catPisosid");

                    b.HasIndex("catTipoDeBienesCatTipoDeBienId");

                    b.HasIndex("catTipoEntradaid");

                    b.HasIndex("catTipoPartidaid");

                    b.ToTable("TblInstrumentalMedico");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblInventarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroInventario")
                        .HasColumnType("text");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblInventarios");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblProveedor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("proveedor")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblProveedor");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblResguardatarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CatServicioid")
                        .HasColumnType("integer");

                    b.Property<string>("RFC")
                        .HasColumnType("text");

                    b.Property<int?>("TblAreaServicioid")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("apellidoDos")
                        .HasColumnType("text");

                    b.Property<string>("apellidoUno")
                        .HasColumnType("text");

                    b.Property<string>("cargo")
                        .HasColumnType("text");

                    b.Property<int?>("catEstatusid")
                        .HasColumnType("integer");

                    b.Property<int?>("catSexoid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoContratoid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTurnoid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.Property<string>("numeroempleado")
                        .HasColumnType("text");

                    b.Property<string>("plaza")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("CatServicioid");

                    b.HasIndex("TblAreaServicioid");

                    b.HasIndex("catEstatusid");

                    b.HasIndex("catSexoid");

                    b.HasIndex("catTipoContratoid");

                    b.HasIndex("catTurnoid");

                    b.ToTable("TblResguardatarios");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblSalidaBien", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<int?>("Idbienesid")
                        .HasColumnType("integer");

                    b.Property<int?>("TblBienesEquMedicoid")
                        .HasColumnType("integer");

                    b.Property<int?>("TblBienesSistemasid")
                        .HasColumnType("integer");

                    b.Property<int?>("TblInstrumentalMedicoid")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("catTipoSalidaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catUnidadDestinoid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("CatTipoDeBienId");

                    b.HasIndex("Idbienesid");

                    b.HasIndex("TblBienesEquMedicoid");

                    b.HasIndex("TblBienesSistemasid");

                    b.HasIndex("TblInstrumentalMedicoid");

                    b.HasIndex("catTipoSalidaid");

                    b.HasIndex("catUnidadDestinoid");

                    b.ToTable("TblSalidaBien");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int?>("IdAreaServicioid")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("RFC")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("cargo")
                        .HasColumnType("text");

                    b.Property<int?>("catEstatusid")
                        .HasColumnType("integer");

                    b.Property<int?>("catRolid")
                        .HasColumnType("integer");

                    b.Property<int?>("catSexoid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoContratoid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTurnoid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idTok")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("numeroempleado")
                        .HasColumnType("text");

                    b.Property<string>("plaza")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("IdAreaServicioid");

                    b.HasIndex("catEstatusid");

                    b.HasIndex("catRolid");

                    b.HasIndex("catSexoid");

                    b.HasIndex("catTipoContratoid");

                    b.HasIndex("catTurnoid");

                    b.ToTable("CtrlUsuarios");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblAreaServicio", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatArea", "catarea")
                        .WithMany("tblAreaServicios")
                        .HasForeignKey("catareaid");

                    b.HasOne("SICOBIM_B.Entities.CatServicio", "catservicio")
                        .WithMany("tblAreaServicios")
                        .HasForeignKey("catservicioid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienes", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.TblProveedor", "IProveedor")
                        .WithMany("tblBienes")
                        .HasForeignKey("IProveedorid");

                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", "IdAreaServicio")
                        .WithMany("tblBienes")
                        .HasForeignKey("IdAreaServicioid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveCabms", "IdClaveCabms")
                        .WithMany("tblBienes")
                        .HasForeignKey("IdClaveCabmsid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveSaica", "IdClaveSaica")
                        .WithMany("tblBienes")
                        .HasForeignKey("IdClaveSaicaid");

                    b.HasOne("SICOBIM_B.Entities.TblContratoBien", "IdContratoBien")
                        .WithMany("tblBienes")
                        .HasForeignKey("IdContratoBienid");

                    b.HasOne("SICOBIM_B.Entities.TblFacturas", "IdFacturas")
                        .WithMany("tblBienes")
                        .HasForeignKey("IdFacturasTblFacturasId");

                    b.HasOne("SICOBIM_B.Entities.TblFederalizacion", "IdFederalizacion")
                        .WithMany("TblBienes")
                        .HasForeignKey("IdFederalizacionid");

                    b.HasOne("SICOBIM_B.Entities.TblInventarios", "IdInventarios")
                        .WithMany("tblBienes")
                        .HasForeignKey("IdInventariosid");

                    b.HasOne("SICOBIM_B.Entities.TblResguardatarios", "IdResguardatarios")
                        .WithMany("tblBienes")
                        .HasForeignKey("IdResguardatariosid");

                    b.HasOne("SICOBIM_B.Entities.CatEstadoDelBien", "catEstadoDelBien")
                        .WithMany("tblBienes")
                        .HasForeignKey("catEstadoDelBienid");

                    b.HasOne("SICOBIM_B.Entities.CatGarantia", "catGarantia")
                        .WithMany("tblBienes")
                        .HasForeignKey("catGarantiaid");

                    b.HasOne("SICOBIM_B.Entities.CatPisos", "catPisos")
                        .WithMany("tblBienes")
                        .HasForeignKey("catPisosid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "catTipoDeBienes")
                        .WithMany("tblBienes")
                        .HasForeignKey("catTipoDeBienesCatTipoDeBienId");

                    b.HasOne("SICOBIM_B.Entities.CatTipoEntrada", "catTipoEntrada")
                        .WithMany("tblBienes")
                        .HasForeignKey("catTipoEntradaid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoPartida", "catTipoPartida")
                        .WithMany("tblBienes")
                        .HasForeignKey("catTipoPartidaid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienesEquMedico", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", "IdAreaServicio")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("IdAreaServicioid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveCabms", "IdClaveCabms")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("IdClaveCabmsid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveSaica", "IdClaveSaica")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("IdClaveSaicaid");

                    b.HasOne("SICOBIM_B.Entities.TblContratoBien", "IdContratoBien")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("IdContratoBienid");

                    b.HasOne("SICOBIM_B.Entities.TblFederalizacion", "IdFederalizacion")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("IdFederalizacionid");

                    b.HasOne("SICOBIM_B.Entities.TblInventarios", "IdInventario")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("IdInventarioid");

                    b.HasOne("SICOBIM_B.Entities.TblProveedor", "IdProveedor")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("IdProveedorid");

                    b.HasOne("SICOBIM_B.Entities.TblResguardatarios", "IdResguardatarios")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("IdResguardatariosid");

                    b.HasOne("SICOBIM_B.Entities.TblFacturas", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("TblFacturasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatEstadoDelBien", "catEstadoDelBien")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("catEstadoDelBienid");

                    b.HasOne("SICOBIM_B.Entities.CatGarantia", "catGarantia")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("catGarantiaid");

                    b.HasOne("SICOBIM_B.Entities.CatPisos", "catPisos")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("catPisosid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "catTipoDeBienes")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("catTipoDeBienesCatTipoDeBienId");

                    b.HasOne("SICOBIM_B.Entities.CatTipoEntrada", "catTipoEntrada")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("catTipoEntradaid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoPartida", "catTipoPartida")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("catTipoPartidaid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienesSistemas", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", "IdAreaServicio")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("IdAreaServicioid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveCabms", "IdClaveCabms")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("IdClaveCabmsid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveSaica", "IdClaveSaica")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("IdClaveSaicaid");

                    b.HasOne("SICOBIM_B.Entities.TblContratoBien", "IdContratoBien")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("IdContratoBienid");

                    b.HasOne("SICOBIM_B.Entities.TblFacturas", "IdFacturas")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("IdFacturasTblFacturasId");

                    b.HasOne("SICOBIM_B.Entities.TblFederalizacion", "IdFederalizacion")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("IdFederalizacionid");

                    b.HasOne("SICOBIM_B.Entities.TblInventarios", "IdInventarios")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("IdInventariosid");

                    b.HasOne("SICOBIM_B.Entities.TblProveedor", "IdProveedor")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("IdProveedorid");

                    b.HasOne("SICOBIM_B.Entities.TblResguardatarios", "IdResguardatarios")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("IdResguardatariosid");

                    b.HasOne("SICOBIM_B.Entities.CatEstadoDelBien", "catEstadoDelBien")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("catEstadoDelBienid");

                    b.HasOne("SICOBIM_B.Entities.CatGarantia", "catGarantia")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("catGarantiaid");

                    b.HasOne("SICOBIM_B.Entities.CatPisos", "catPisos")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("catPisosid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "catTipoDeBienes")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("catTipoDeBienesCatTipoDeBienId");

                    b.HasOne("SICOBIM_B.Entities.CatTipoEntrada", "catTipoEntrada")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("catTipoEntradaid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoPartida", "catTipoPartida")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("catTipoPartidaid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblClaveCabms", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany()
                        .HasForeignKey("CatTipoDeBienId");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblClaveSaica", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany()
                        .HasForeignKey("CatTipoDeBienId");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblConfPerfil", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatPermiso", "IdPermiso")
                        .WithMany()
                        .HasForeignKey("IdPermisoid");

                    b.HasOne("SICOBIM_B.Entities.CatRol", "IdRol")
                        .WithMany()
                        .HasForeignKey("IdRolid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblContratoBien", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany()
                        .HasForeignKey("CatTipoDeBienId");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblFacturas", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("tblFacturas")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblFederalizacion", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany()
                        .HasForeignKey("CatTipoDeBienId");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblInstrumentalMedico", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", "IdAreaServicio")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("IdAreaServicioid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveCabms", "IdClaveCambs")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("IdClaveCambsid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveSaica", "IdClaveSaica")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("IdClaveSaicaid");

                    b.HasOne("SICOBIM_B.Entities.TblContratoBien", "IdContratoBien")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("IdContratoBienid");

                    b.HasOne("SICOBIM_B.Entities.TblFacturas", "IdFacturas")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("IdFacturasTblFacturasId");

                    b.HasOne("SICOBIM_B.Entities.TblFederalizacion", "IdFederalizacion")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("IdFederalizacionid");

                    b.HasOne("SICOBIM_B.Entities.TblInventarios", "IdInventarios")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("IdInventariosid");

                    b.HasOne("SICOBIM_B.Entities.TblProveedor", "IdProveedor")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("IdProveedorid");

                    b.HasOne("SICOBIM_B.Entities.TblResguardatarios", "IdResguardatarios")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("IdResguardatariosid");

                    b.HasOne("SICOBIM_B.Entities.CatEstadoDelBien", "catEstadoDelBien")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("catEstadoDelBienid");

                    b.HasOne("SICOBIM_B.Entities.CatGarantia", "catGarantia")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("catGarantiaid");

                    b.HasOne("SICOBIM_B.Entities.CatPisos", "catPisos")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("catPisosid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "catTipoDeBienes")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("catTipoDeBienesCatTipoDeBienId");

                    b.HasOne("SICOBIM_B.Entities.CatTipoEntrada", "catTipoEntrada")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("catTipoEntradaid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoPartida", "catTipoPartida")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("catTipoPartidaid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblInventarios", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany()
                        .HasForeignKey("CatTipoDeBienId");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblProveedor", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany()
                        .HasForeignKey("CatTipoDeBienId");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblResguardatarios", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatServicio", "CatServicio")
                        .WithMany()
                        .HasForeignKey("CatServicioid");

                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", null)
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("TblAreaServicioid");

                    b.HasOne("SICOBIM_B.Entities.CatEstatus", "catEstatus")
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("catEstatusid");

                    b.HasOne("SICOBIM_B.Entities.CatSexo", "catSexo")
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("catSexoid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoContrato", "catTipoContrato")
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("catTipoContratoid");

                    b.HasOne("SICOBIM_B.Entities.CatTurno", "catTurno")
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("catTurnoid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblSalidaBien", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany()
                        .HasForeignKey("CatTipoDeBienId");

                    b.HasOne("SICOBIM_B.Entities.TblBienes", "Idbienes")
                        .WithMany("tblSalidaBien")
                        .HasForeignKey("Idbienesid");

                    b.HasOne("SICOBIM_B.Entities.TblBienesEquMedico", null)
                        .WithMany("tblSalidaBien")
                        .HasForeignKey("TblBienesEquMedicoid");

                    b.HasOne("SICOBIM_B.Entities.TblBienesSistemas", null)
                        .WithMany("tblSalidaBien")
                        .HasForeignKey("TblBienesSistemasid");

                    b.HasOne("SICOBIM_B.Entities.TblInstrumentalMedico", null)
                        .WithMany("tblSalidaBien")
                        .HasForeignKey("TblInstrumentalMedicoid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoSalida", "catTipoSalida")
                        .WithMany("tblsalidaBien")
                        .HasForeignKey("catTipoSalidaid");

                    b.HasOne("SICOBIM_B.Entities.CatUnidadDestino", "catUnidadDestino")
                        .WithMany("tblsalidaBien")
                        .HasForeignKey("catUnidadDestinoid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.User", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", "IdAreaServicio")
                        .WithMany("users")
                        .HasForeignKey("IdAreaServicioid");

                    b.HasOne("SICOBIM_B.Entities.CatEstatus", "catEstatus")
                        .WithMany("users")
                        .HasForeignKey("catEstatusid");

                    b.HasOne("SICOBIM_B.Entities.CatRol", "catRol")
                        .WithMany("user")
                        .HasForeignKey("catRolid");

                    b.HasOne("SICOBIM_B.Entities.CatSexo", "catSexo")
                        .WithMany("users")
                        .HasForeignKey("catSexoid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoContrato", "catTipoContrato")
                        .WithMany("users")
                        .HasForeignKey("catTipoContratoid");

                    b.HasOne("SICOBIM_B.Entities.CatTurno", "catTurno")
                        .WithMany("users")
                        .HasForeignKey("catTurnoid");

                    b.OwnsMany("SICOBIM_B.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<DateTime>("Created")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("text");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("text");

                            b1.Property<string>("Token")
                                .HasColumnType("text");

                            b1.Property<int>("Userid")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("Userid");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("Userid");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
