// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SICOBIM_B.Data;

namespace SICOBIM_B.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201015030205_jzlz_16")]
    partial class jzlz_16
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SICOBIM_B.Entities.CatArea", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("area")
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idusuarioMod")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioAlta")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatArea");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatEstadoDelBien", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatEstadoDelBien");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatEstatus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("estatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatEstatus");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatGarantia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("añosGarantia")
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatGarantia");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatPermiso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("permiso")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatPermiso");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatPisos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("piso")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatPiso");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatRol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("idusuarioMod")
                        .HasColumnType("integer");

                    b.Property<string>("rol")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("CatRol");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatServicio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idusuarioMod")
                        .HasColumnType("integer");

                    b.Property<string>("servicio")
                        .HasColumnType("text");

                    b.Property<int>("usuarioAlta")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatServicio");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatSexo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("sexo")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatSexo");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoContrato", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("contrato")
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatTipoContrato");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoDeBien", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("TipodeBien")
                        .HasColumnType("text");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatTipoDeBien");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoEntrada", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("tipoentrada")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatTipoEntrada");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoPartida", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("partidapresupestual")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatTipoPartida");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoSalida", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("tiposalida")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatTipoSalida");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTurno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("turno")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatTurno");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatUnidadDestino", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("destino")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("idusuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatUnidadDestino");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblAreaServicio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("catareaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catservicioid")
                        .HasColumnType("integer");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idarea")
                        .HasColumnType("integer");

                    b.Property<int>("idservicio")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("catareaid");

                    b.HasIndex("catservicioid");

                    b.ToTable("TblAreaServicio");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("catEstadoDelBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("catGarantiaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catPisosid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoDeBienesid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoEntradaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoPartidaid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idAñosGarantia")
                        .HasColumnType("integer");

                    b.Property<int>("idEstadoFisico")
                        .HasColumnType("integer");

                    b.Property<int>("idResguardatario")
                        .HasColumnType("integer");

                    b.Property<int>("idServicio")
                        .HasColumnType("integer");

                    b.Property<int>("idTipoBien")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("idclaveCambs")
                        .HasColumnType("integer");

                    b.Property<string>("idclaveSaica")
                        .HasColumnType("text");

                    b.Property<int>("idcontrato")
                        .HasColumnType("integer");

                    b.Property<int>("identrada")
                        .HasColumnType("integer");

                    b.Property<int>("idfactura")
                        .HasColumnType("integer");

                    b.Property<int>("idfederalizacion")
                        .HasColumnType("integer");

                    b.Property<int>("idinventario")
                        .HasColumnType("integer");

                    b.Property<int>("idpiso")
                        .HasColumnType("integer");

                    b.Property<int>("idproveedor")
                        .HasColumnType("integer");

                    b.Property<int>("idtipopartida")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("serie")
                        .HasColumnType("text");

                    b.Property<int?>("tblAreaServicioid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblClaveCambsid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblClaveSaicaid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblContratoBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblFacturasid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblFederalizacionid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblInventariosid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblProveedorid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblResguardatariosid")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("catEstadoDelBienid");

                    b.HasIndex("catGarantiaid");

                    b.HasIndex("catPisosid");

                    b.HasIndex("catTipoDeBienesid");

                    b.HasIndex("catTipoEntradaid");

                    b.HasIndex("catTipoPartidaid");

                    b.HasIndex("tblAreaServicioid");

                    b.HasIndex("tblClaveCambsid");

                    b.HasIndex("tblClaveSaicaid");

                    b.HasIndex("tblContratoBienid");

                    b.HasIndex("tblFacturasid");

                    b.HasIndex("tblFederalizacionid");

                    b.HasIndex("tblInventariosid");

                    b.HasIndex("tblProveedorid");

                    b.HasIndex("tblResguardatariosid");

                    b.ToTable("TblBienesMuebles");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienesEquMedico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("catEstadoDelBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("catGarantiaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catPisosid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoDeBienesid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoEntradaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoPartidaid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idAñosGarantia")
                        .HasColumnType("integer");

                    b.Property<int>("idEstadoFisico")
                        .HasColumnType("integer");

                    b.Property<int>("idResguardatario")
                        .HasColumnType("integer");

                    b.Property<int>("idServicio")
                        .HasColumnType("integer");

                    b.Property<int>("idTipoBien")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("idclaveCambs")
                        .HasColumnType("integer");

                    b.Property<string>("idclaveSaica")
                        .HasColumnType("text");

                    b.Property<int>("idcontrato")
                        .HasColumnType("integer");

                    b.Property<int>("identrada")
                        .HasColumnType("integer");

                    b.Property<int>("idfactura")
                        .HasColumnType("integer");

                    b.Property<int>("idfederalizacion")
                        .HasColumnType("integer");

                    b.Property<int>("idinventario")
                        .HasColumnType("integer");

                    b.Property<int>("idpiso")
                        .HasColumnType("integer");

                    b.Property<int>("idproveedor")
                        .HasColumnType("integer");

                    b.Property<int>("idtipopartida")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("serie")
                        .HasColumnType("text");

                    b.Property<int?>("tblAreaServicioid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblClaveCambsid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblClaveSaicaid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblContratoBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblFacturasid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblFederalizacionid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblInventariosid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblProveedorid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblResguardatariosid")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("catEstadoDelBienid");

                    b.HasIndex("catGarantiaid");

                    b.HasIndex("catPisosid");

                    b.HasIndex("catTipoDeBienesid");

                    b.HasIndex("catTipoEntradaid");

                    b.HasIndex("catTipoPartidaid");

                    b.HasIndex("tblAreaServicioid");

                    b.HasIndex("tblClaveCambsid");

                    b.HasIndex("tblClaveSaicaid");

                    b.HasIndex("tblContratoBienid");

                    b.HasIndex("tblFacturasid");

                    b.HasIndex("tblFederalizacionid");

                    b.HasIndex("tblInventariosid");

                    b.HasIndex("tblProveedorid");

                    b.HasIndex("tblResguardatariosid");

                    b.ToTable("TblBienesEquMedico");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienesSistemas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("catEstadoDelBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("catGarantiaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catPisosid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoDeBienesid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoEntradaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoPartidaid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idAñosGarantia")
                        .HasColumnType("integer");

                    b.Property<int>("idEstadoFisico")
                        .HasColumnType("integer");

                    b.Property<int>("idResguardatario")
                        .HasColumnType("integer");

                    b.Property<int>("idServicio")
                        .HasColumnType("integer");

                    b.Property<int>("idTipoBien")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("idclaveCambs")
                        .HasColumnType("integer");

                    b.Property<string>("idclaveSaica")
                        .HasColumnType("text");

                    b.Property<int>("idcontrato")
                        .HasColumnType("integer");

                    b.Property<int>("identrada")
                        .HasColumnType("integer");

                    b.Property<int>("idfactura")
                        .HasColumnType("integer");

                    b.Property<int>("idfederalizacion")
                        .HasColumnType("integer");

                    b.Property<int>("idinventario")
                        .HasColumnType("integer");

                    b.Property<int>("idpiso")
                        .HasColumnType("integer");

                    b.Property<int>("idproveedor")
                        .HasColumnType("integer");

                    b.Property<int>("idtipopartida")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("serie")
                        .HasColumnType("text");

                    b.Property<int?>("tblAreaServicioid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblClaveCambsid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblClaveSaicaid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblContratoBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblFacturasid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblFederalizacionid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblInventariosid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblProveedorid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblResguardatariosid")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("catEstadoDelBienid");

                    b.HasIndex("catGarantiaid");

                    b.HasIndex("catPisosid");

                    b.HasIndex("catTipoDeBienesid");

                    b.HasIndex("catTipoEntradaid");

                    b.HasIndex("catTipoPartidaid");

                    b.HasIndex("tblAreaServicioid");

                    b.HasIndex("tblClaveCambsid");

                    b.HasIndex("tblClaveSaicaid");

                    b.HasIndex("tblContratoBienid");

                    b.HasIndex("tblFacturasid");

                    b.HasIndex("tblFederalizacionid");

                    b.HasIndex("tblInventariosid");

                    b.HasIndex("tblProveedorid");

                    b.HasIndex("tblResguardatariosid");

                    b.ToTable("TblBienesSistemas");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblClaveCambs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("clavecambs")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("TblClaveCambs");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblClaveSaica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("clavesaica")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("TblClaveSaica");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblConfPerfil", b =>
                {
                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("idPermiso")
                        .HasColumnType("integer");

                    b.Property<int?>("idRol")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasIndex("idPermiso");

                    b.HasIndex("idRol");

                    b.ToTable("TblConfPerfil");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblContratoBien", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("contratobien")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("TblContratoBien");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblFacturas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("IVA")
                        .HasColumnType("double precision");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<double>("costoTotal")
                        .HasColumnType("double precision");

                    b.Property<string>("facturas")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<double>("subtotal")
                        .HasColumnType("double precision");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("TblFacturas");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblFederalizacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("federalizacion")
                        .HasColumnType("text");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("TblFederalizacion");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblInstrumentalMedico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("catEstadoDelBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("catGarantiaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catPisosid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoDeBienesid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoEntradaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoPartidaid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idAñosGarantia")
                        .HasColumnType("integer");

                    b.Property<int>("idEstadoFisico")
                        .HasColumnType("integer");

                    b.Property<int>("idResguardatario")
                        .HasColumnType("integer");

                    b.Property<int>("idServicio")
                        .HasColumnType("integer");

                    b.Property<int>("idTipoBien")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("idclaveCambs")
                        .HasColumnType("integer");

                    b.Property<string>("idclaveSaica")
                        .HasColumnType("text");

                    b.Property<int>("idcontrato")
                        .HasColumnType("integer");

                    b.Property<int>("identrada")
                        .HasColumnType("integer");

                    b.Property<int>("idfactura")
                        .HasColumnType("integer");

                    b.Property<int>("idfederalizacion")
                        .HasColumnType("integer");

                    b.Property<int>("idinventario")
                        .HasColumnType("integer");

                    b.Property<int>("idpiso")
                        .HasColumnType("integer");

                    b.Property<int>("idproveedor")
                        .HasColumnType("integer");

                    b.Property<int>("idtipopartida")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("serie")
                        .HasColumnType("text");

                    b.Property<int?>("tblAreaServicioid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblClaveCambsid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblClaveSaicaid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblContratoBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblFacturasid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblFederalizacionid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblInventariosid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblProveedorid")
                        .HasColumnType("integer");

                    b.Property<int?>("tblResguardatariosid")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("catEstadoDelBienid");

                    b.HasIndex("catGarantiaid");

                    b.HasIndex("catPisosid");

                    b.HasIndex("catTipoDeBienesid");

                    b.HasIndex("catTipoEntradaid");

                    b.HasIndex("catTipoPartidaid");

                    b.HasIndex("tblAreaServicioid");

                    b.HasIndex("tblClaveCambsid");

                    b.HasIndex("tblClaveSaicaid");

                    b.HasIndex("tblContratoBienid");

                    b.HasIndex("tblFacturasid");

                    b.HasIndex("tblFederalizacionid");

                    b.HasIndex("tblInventariosid");

                    b.HasIndex("tblProveedorid");

                    b.HasIndex("tblResguardatariosid");

                    b.ToTable("TblInstrumentalMedico");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblInventarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("NumeroInventario")
                        .HasColumnType("text");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("TblInventarios");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblProveedor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("proveedor")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("TblProveedor");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblResguardatarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CatServicioid")
                        .HasColumnType("integer");

                    b.Property<string>("RFC")
                        .HasColumnType("text");

                    b.Property<int?>("TblAreaServicioid")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("apellidoDos")
                        .HasColumnType("text");

                    b.Property<string>("apellidoUno")
                        .HasColumnType("text");

                    b.Property<string>("cargo")
                        .HasColumnType("text");

                    b.Property<int?>("catEstatusid")
                        .HasColumnType("integer");

                    b.Property<int?>("catSexoid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoContratoid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTurnoid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idEstatus")
                        .HasColumnType("integer");

                    b.Property<int>("idServicio")
                        .HasColumnType("integer");

                    b.Property<int>("idSexo")
                        .HasColumnType("integer");

                    b.Property<int>("idTipoContrato")
                        .HasColumnType("integer");

                    b.Property<int>("idTurno")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.Property<string>("numeroempleado")
                        .HasColumnType("text");

                    b.Property<string>("plaza")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("CatServicioid");

                    b.HasIndex("TblAreaServicioid");

                    b.HasIndex("catEstatusid");

                    b.HasIndex("catSexoid");

                    b.HasIndex("catTipoContratoid");

                    b.HasIndex("catTurnoid");

                    b.ToTable("TblResguardatarios");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblSalidaBien", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("TblBienesEquMedicoid")
                        .HasColumnType("integer");

                    b.Property<int?>("TblBienesSistemasid")
                        .HasColumnType("integer");

                    b.Property<int?>("TblInstrumentalMedicoid")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("catTipoSalidaid")
                        .HasColumnType("integer");

                    b.Property<int?>("catUnidadDestinoid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("idbien")
                        .HasColumnType("integer");

                    b.Property<int>("idtiposalida")
                        .HasColumnType("integer");

                    b.Property<int>("idunidaddestino")
                        .HasColumnType("integer");

                    b.Property<int?>("tblbienesid")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("TblBienesEquMedicoid");

                    b.HasIndex("TblBienesSistemasid");

                    b.HasIndex("TblInstrumentalMedicoid");

                    b.HasIndex("catTipoSalidaid");

                    b.HasIndex("catUnidadDestinoid");

                    b.HasIndex("tblbienesid");

                    b.ToTable("TblSalidaBien");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("RFC")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("cargo")
                        .HasColumnType("text");

                    b.Property<int?>("catEstatusid")
                        .HasColumnType("integer");

                    b.Property<int?>("catSexoid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTipoContratoid")
                        .HasColumnType("integer");

                    b.Property<int?>("catTurnoid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idServicio")
                        .HasColumnType("integer");

                    b.Property<int>("idSexo")
                        .HasColumnType("integer");

                    b.Property<int>("idTok")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("idestatus")
                        .HasColumnType("integer");

                    b.Property<int>("idrol")
                        .HasColumnType("integer");

                    b.Property<int>("idtipocontrato")
                        .HasColumnType("integer");

                    b.Property<int>("idturno")
                        .HasColumnType("integer");

                    b.Property<string>("numeroempleado")
                        .HasColumnType("text");

                    b.Property<string>("plaza")
                        .HasColumnType("text");

                    b.Property<int?>("tblAreaServicioid")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("catEstatusid");

                    b.HasIndex("catSexoid");

                    b.HasIndex("catTipoContratoid");

                    b.HasIndex("catTurnoid");

                    b.HasIndex("tblAreaServicioid");

                    b.ToTable("CtrlUsuarios");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblAreaServicio", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatArea", "catarea")
                        .WithMany("tblAreaServicios")
                        .HasForeignKey("catareaid");

                    b.HasOne("SICOBIM_B.Entities.CatServicio", "catservicio")
                        .WithMany("tblAreaServicios")
                        .HasForeignKey("catservicioid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienes", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatEstadoDelBien", "catEstadoDelBien")
                        .WithMany("tblBienes")
                        .HasForeignKey("catEstadoDelBienid");

                    b.HasOne("SICOBIM_B.Entities.CatGarantia", "catGarantia")
                        .WithMany("tblBienes")
                        .HasForeignKey("catGarantiaid");

                    b.HasOne("SICOBIM_B.Entities.CatPisos", "catPisos")
                        .WithMany("tblBienes")
                        .HasForeignKey("catPisosid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "catTipoDeBienes")
                        .WithMany("tblBienes")
                        .HasForeignKey("catTipoDeBienesid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoEntrada", "catTipoEntrada")
                        .WithMany("tblBienes")
                        .HasForeignKey("catTipoEntradaid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoPartida", "catTipoPartida")
                        .WithMany("tblBienes")
                        .HasForeignKey("catTipoPartidaid");

                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", "tblAreaServicio")
                        .WithMany("tblBienes")
                        .HasForeignKey("tblAreaServicioid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveCambs", "tblClaveCambs")
                        .WithMany("tblBienes")
                        .HasForeignKey("tblClaveCambsid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveSaica", "tblClaveSaica")
                        .WithMany("tblBienes")
                        .HasForeignKey("tblClaveSaicaid");

                    b.HasOne("SICOBIM_B.Entities.TblContratoBien", "tblContratoBien")
                        .WithMany("tblBienes")
                        .HasForeignKey("tblContratoBienid");

                    b.HasOne("SICOBIM_B.Entities.TblFacturas", "tblFacturas")
                        .WithMany("tblBienes")
                        .HasForeignKey("tblFacturasid");

                    b.HasOne("SICOBIM_B.Entities.TblFederalizacion", "tblFederalizacion")
                        .WithMany("tblBienes")
                        .HasForeignKey("tblFederalizacionid");

                    b.HasOne("SICOBIM_B.Entities.TblInventarios", "tblInventarios")
                        .WithMany("tblBieness")
                        .HasForeignKey("tblInventariosid");

                    b.HasOne("SICOBIM_B.Entities.TblProveedor", "tblProveedor")
                        .WithMany("tblBienes")
                        .HasForeignKey("tblProveedorid");

                    b.HasOne("SICOBIM_B.Entities.TblResguardatarios", "tblResguardatarios")
                        .WithMany("tblBienes")
                        .HasForeignKey("tblResguardatariosid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienesEquMedico", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatEstadoDelBien", "catEstadoDelBien")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("catEstadoDelBienid");

                    b.HasOne("SICOBIM_B.Entities.CatGarantia", "catGarantia")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("catGarantiaid");

                    b.HasOne("SICOBIM_B.Entities.CatPisos", "catPisos")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("catPisosid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "catTipoDeBienes")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("catTipoDeBienesid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoEntrada", "catTipoEntrada")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("catTipoEntradaid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoPartida", "catTipoPartida")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("catTipoPartidaid");

                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", "tblAreaServicio")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("tblAreaServicioid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveCambs", "tblClaveCambs")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("tblClaveCambsid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveSaica", "tblClaveSaica")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("tblClaveSaicaid");

                    b.HasOne("SICOBIM_B.Entities.TblContratoBien", "tblContratoBien")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("tblContratoBienid");

                    b.HasOne("SICOBIM_B.Entities.TblFacturas", "tblFacturas")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("tblFacturasid");

                    b.HasOne("SICOBIM_B.Entities.TblFederalizacion", "tblFederalizacion")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("tblFederalizacionid");

                    b.HasOne("SICOBIM_B.Entities.TblInventarios", "tblInventarios")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("tblInventariosid");

                    b.HasOne("SICOBIM_B.Entities.TblProveedor", "tblProveedor")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("tblProveedorid");

                    b.HasOne("SICOBIM_B.Entities.TblResguardatarios", "tblResguardatarios")
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("tblResguardatariosid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienesSistemas", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatEstadoDelBien", "catEstadoDelBien")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("catEstadoDelBienid");

                    b.HasOne("SICOBIM_B.Entities.CatGarantia", "catGarantia")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("catGarantiaid");

                    b.HasOne("SICOBIM_B.Entities.CatPisos", "catPisos")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("catPisosid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "catTipoDeBienes")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("catTipoDeBienesid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoEntrada", "catTipoEntrada")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("catTipoEntradaid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoPartida", "catTipoPartida")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("catTipoPartidaid");

                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", "tblAreaServicio")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("tblAreaServicioid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveCambs", "tblClaveCambs")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("tblClaveCambsid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveSaica", "tblClaveSaica")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("tblClaveSaicaid");

                    b.HasOne("SICOBIM_B.Entities.TblContratoBien", "tblContratoBien")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("tblContratoBienid");

                    b.HasOne("SICOBIM_B.Entities.TblFacturas", "tblFacturas")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("tblFacturasid");

                    b.HasOne("SICOBIM_B.Entities.TblFederalizacion", "tblFederalizacion")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("tblFederalizacionid");

                    b.HasOne("SICOBIM_B.Entities.TblInventarios", "tblInventarios")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("tblInventariosid");

                    b.HasOne("SICOBIM_B.Entities.TblProveedor", "tblProveedor")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("tblProveedorid");

                    b.HasOne("SICOBIM_B.Entities.TblResguardatarios", "tblResguardatarios")
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("tblResguardatariosid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblConfPerfil", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatPermiso", "CatPermiso")
                        .WithMany()
                        .HasForeignKey("idPermiso");

                    b.HasOne("SICOBIM_B.Entities.CatRol", "CatRol")
                        .WithMany()
                        .HasForeignKey("idRol");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblInstrumentalMedico", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatEstadoDelBien", "catEstadoDelBien")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("catEstadoDelBienid");

                    b.HasOne("SICOBIM_B.Entities.CatGarantia", "catGarantia")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("catGarantiaid");

                    b.HasOne("SICOBIM_B.Entities.CatPisos", "catPisos")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("catPisosid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", "catTipoDeBienes")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("catTipoDeBienesid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoEntrada", "catTipoEntrada")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("catTipoEntradaid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoPartida", "catTipoPartida")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("catTipoPartidaid");

                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", "tblAreaServicio")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("tblAreaServicioid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveCambs", "tblClaveCambs")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("tblClaveCambsid");

                    b.HasOne("SICOBIM_B.Entities.TblClaveSaica", "tblClaveSaica")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("tblClaveSaicaid");

                    b.HasOne("SICOBIM_B.Entities.TblContratoBien", "tblContratoBien")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("tblContratoBienid");

                    b.HasOne("SICOBIM_B.Entities.TblFacturas", "tblFacturas")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("tblFacturasid");

                    b.HasOne("SICOBIM_B.Entities.TblFederalizacion", "tblFederalizacion")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("tblFederalizacionid");

                    b.HasOne("SICOBIM_B.Entities.TblInventarios", "tblInventarios")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("tblInventariosid");

                    b.HasOne("SICOBIM_B.Entities.TblProveedor", "tblProveedor")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("tblProveedorid");

                    b.HasOne("SICOBIM_B.Entities.TblResguardatarios", "tblResguardatarios")
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("tblResguardatariosid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblResguardatarios", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatServicio", "CatServicio")
                        .WithMany()
                        .HasForeignKey("CatServicioid");

                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", null)
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("TblAreaServicioid");

                    b.HasOne("SICOBIM_B.Entities.CatEstatus", "catEstatus")
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("catEstatusid");

                    b.HasOne("SICOBIM_B.Entities.CatSexo", "catSexo")
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("catSexoid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoContrato", "catTipoContrato")
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("catTipoContratoid");

                    b.HasOne("SICOBIM_B.Entities.CatTurno", "catTurno")
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("catTurnoid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblSalidaBien", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.TblBienesEquMedico", null)
                        .WithMany("tblSalidaBien")
                        .HasForeignKey("TblBienesEquMedicoid");

                    b.HasOne("SICOBIM_B.Entities.TblBienesSistemas", null)
                        .WithMany("tblSalidaBien")
                        .HasForeignKey("TblBienesSistemasid");

                    b.HasOne("SICOBIM_B.Entities.TblInstrumentalMedico", null)
                        .WithMany("tblSalidaBien")
                        .HasForeignKey("TblInstrumentalMedicoid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoSalida", "catTipoSalida")
                        .WithMany("tblsalidaBien")
                        .HasForeignKey("catTipoSalidaid");

                    b.HasOne("SICOBIM_B.Entities.CatUnidadDestino", "catUnidadDestino")
                        .WithMany("tblsalidaBien")
                        .HasForeignKey("catUnidadDestinoid");

                    b.HasOne("SICOBIM_B.Entities.TblBienes", "tblbienes")
                        .WithMany("tblSalidaBien")
                        .HasForeignKey("tblbienesid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.User", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatEstatus", "catEstatus")
                        .WithMany("users")
                        .HasForeignKey("catEstatusid");

                    b.HasOne("SICOBIM_B.Entities.CatSexo", "catSexo")
                        .WithMany("users")
                        .HasForeignKey("catSexoid");

                    b.HasOne("SICOBIM_B.Entities.CatTipoContrato", "catTipoContrato")
                        .WithMany("users")
                        .HasForeignKey("catTipoContratoid");

                    b.HasOne("SICOBIM_B.Entities.CatTurno", "catTurno")
                        .WithMany("users")
                        .HasForeignKey("catTurnoid");

                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", "tblAreaServicio")
                        .WithMany("users")
                        .HasForeignKey("tblAreaServicioid");

                    b.OwnsMany("SICOBIM_B.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<DateTime>("Created")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("text");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("text");

                            b1.Property<string>("Token")
                                .HasColumnType("text");

                            b1.Property<int>("Userid")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("Userid");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("Userid");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
