// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SICOBIM_B.Data;

namespace SICOBIM_B.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201111013143_jzlz_37")]
    partial class jzlz_37
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SICOBIM_B.Entities.CatArea", b =>
                {
                    b.Property<int>("CatAreaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("area")
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idusuarioMod")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioAlta")
                        .HasColumnType("integer");

                    b.HasKey("CatAreaid");

                    b.ToTable("CatArea");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatEstadoDelBien", b =>
                {
                    b.Property<int>("CatEstadoDelBienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("CatEstadoDelBienId");

                    b.ToTable("CatEstadoDelBien");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatEstatus", b =>
                {
                    b.Property<int>("CatEstatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("estatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("CatEstatusId");

                    b.ToTable("CatEstatus");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatGarantia", b =>
                {
                    b.Property<int>("CatGarantiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("añosGarantia")
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("CatGarantiaId");

                    b.ToTable("CatGarantia");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatPermiso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("permiso")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("CatPermiso");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatPisos", b =>
                {
                    b.Property<int>("CatPisosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("piso")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("CatPisosId");

                    b.ToTable("CatPiso");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatRol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("idusuarioMod")
                        .HasColumnType("integer");

                    b.Property<string>("rol")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("CatRol");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatServicio", b =>
                {
                    b.Property<int>("CatServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idusuarioMod")
                        .HasColumnType("integer");

                    b.Property<string>("servicio")
                        .HasColumnType("text");

                    b.Property<int>("usuarioAlta")
                        .HasColumnType("integer");

                    b.HasKey("CatServicioId");

                    b.ToTable("CatServicio");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatSexo", b =>
                {
                    b.Property<int>("CatSexoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("sexo")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("CatSexoId");

                    b.ToTable("CatSexo");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoContrato", b =>
                {
                    b.Property<int>("CatTipoContratoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("contrato")
                        .HasColumnType("text");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("CatTipoContratoId");

                    b.ToTable("CatTipoContrato");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoDeBien", b =>
                {
                    b.Property<int>("CatTipoDeBienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("TipodeBien")
                        .HasColumnType("text");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("CatTipoDeBienId");

                    b.ToTable("CatTipoDeBien");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoEntrada", b =>
                {
                    b.Property<int>("CatTipoEntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("tipoentrada")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("CatTipoEntradaId");

                    b.ToTable("CatTipoEntrada");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoPartida", b =>
                {
                    b.Property<int>("CatTipoPartidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("partidapresupestual")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("CatTipoPartidaId");

                    b.ToTable("CatTipoPartida");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTipoSalida", b =>
                {
                    b.Property<int>("CatTipoSalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("tiposalida")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("CatTipoSalidaId");

                    b.ToTable("CatTipoSalida");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatTurno", b =>
                {
                    b.Property<int>("CatTurnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("turno")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("CatTurnoId");

                    b.ToTable("CatTurno");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.CatUnidadDestino", b =>
                {
                    b.Property<int>("CatUnidadDestinoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("destino")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("idusuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("CatUnidadDestinoId");

                    b.ToTable("CatUnidadDestino");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblAreaServicio", b =>
                {
                    b.Property<int>("TblAreaServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatAreaid")
                        .HasColumnType("integer");

                    b.Property<int>("CatServicioId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblAreaServicioId");

                    b.HasIndex("CatAreaid");

                    b.HasIndex("CatServicioId");

                    b.ToTable("TblAreaServicio");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienes", b =>
                {
                    b.Property<int>("TblBienesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatEstadoDelBienId")
                        .HasColumnType("integer");

                    b.Property<int>("CatGarantiaId")
                        .HasColumnType("integer");

                    b.Property<int>("CatPisosId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoEntradaId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoPartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("TblAreaServicioId")
                        .HasColumnType("integer");

                    b.Property<int>("TblClaveCabmsId")
                        .HasColumnType("integer");

                    b.Property<int>("TblClaveSaicaId")
                        .HasColumnType("integer");

                    b.Property<int>("TblContratoBienId")
                        .HasColumnType("integer");

                    b.Property<int>("TblFacturasId")
                        .HasColumnType("integer");

                    b.Property<int>("TblFederalizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("TblInventariosId")
                        .HasColumnType("integer");

                    b.Property<int>("TblProveedorId")
                        .HasColumnType("integer");

                    b.Property<int>("TblResguardatariosId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("serie")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblBienesId");

                    b.HasIndex("CatEstadoDelBienId");

                    b.HasIndex("CatGarantiaId");

                    b.HasIndex("CatPisosId");

                    b.HasIndex("CatTipoDeBienId");

                    b.HasIndex("CatTipoEntradaId");

                    b.HasIndex("CatTipoPartidaId");

                    b.HasIndex("TblAreaServicioId");

                    b.HasIndex("TblClaveCabmsId");

                    b.HasIndex("TblClaveSaicaId");

                    b.HasIndex("TblContratoBienId");

                    b.HasIndex("TblFacturasId");

                    b.HasIndex("TblFederalizacionId");

                    b.HasIndex("TblInventariosId");

                    b.HasIndex("TblProveedorId");

                    b.HasIndex("TblResguardatariosId");

                    b.ToTable("TblBienesMuebles");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienesEquMedico", b =>
                {
                    b.Property<int>("TblBienesEquMedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatEstadoDelBienId")
                        .HasColumnType("integer");

                    b.Property<int>("CatGarantiaId")
                        .HasColumnType("integer");

                    b.Property<int>("CatPisosId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoEntradaId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoPartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("TblAreaServicioId")
                        .HasColumnType("integer");

                    b.Property<int>("TblClaveCabmsId")
                        .HasColumnType("integer");

                    b.Property<int>("TblClaveSaicaId")
                        .HasColumnType("integer");

                    b.Property<int>("TblContratoBienId")
                        .HasColumnType("integer");

                    b.Property<int>("TblFacturasId")
                        .HasColumnType("integer");

                    b.Property<int>("TblFederalizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("TblInventariosId")
                        .HasColumnType("integer");

                    b.Property<int>("TblProveedorId")
                        .HasColumnType("integer");

                    b.Property<int>("TblResguardatariosId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("serie")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblBienesEquMedicoId");

                    b.HasIndex("CatEstadoDelBienId");

                    b.HasIndex("CatGarantiaId");

                    b.HasIndex("CatPisosId");

                    b.HasIndex("CatTipoDeBienId");

                    b.HasIndex("CatTipoEntradaId");

                    b.HasIndex("CatTipoPartidaId");

                    b.HasIndex("TblAreaServicioId");

                    b.HasIndex("TblClaveCabmsId");

                    b.HasIndex("TblClaveSaicaId");

                    b.HasIndex("TblContratoBienId");

                    b.HasIndex("TblFacturasId");

                    b.HasIndex("TblFederalizacionId");

                    b.HasIndex("TblInventariosId");

                    b.HasIndex("TblProveedorId");

                    b.HasIndex("TblResguardatariosId");

                    b.ToTable("TblBienesEquMedico");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienesSistemas", b =>
                {
                    b.Property<int>("TblBienesSistemasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatEstadoDelBienId")
                        .HasColumnType("integer");

                    b.Property<int>("CatGarantiaId")
                        .HasColumnType("integer");

                    b.Property<int>("CatPisosId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoEntradaId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoPartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("TblAreaServicioId")
                        .HasColumnType("integer");

                    b.Property<int>("TblClaveCabmsId")
                        .HasColumnType("integer");

                    b.Property<int>("TblClaveSaicaId")
                        .HasColumnType("integer");

                    b.Property<int>("TblContratoBienId")
                        .HasColumnType("integer");

                    b.Property<int>("TblFacturasId")
                        .HasColumnType("integer");

                    b.Property<int>("TblFederalizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("TblInventariosId")
                        .HasColumnType("integer");

                    b.Property<int>("TblProveedorId")
                        .HasColumnType("integer");

                    b.Property<int>("TblResguardatariosId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("serie")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblBienesSistemasId");

                    b.HasIndex("CatEstadoDelBienId");

                    b.HasIndex("CatGarantiaId");

                    b.HasIndex("CatPisosId");

                    b.HasIndex("CatTipoDeBienId");

                    b.HasIndex("CatTipoEntradaId");

                    b.HasIndex("CatTipoPartidaId");

                    b.HasIndex("TblAreaServicioId");

                    b.HasIndex("TblClaveCabmsId");

                    b.HasIndex("TblClaveSaicaId");

                    b.HasIndex("TblContratoBienId");

                    b.HasIndex("TblFacturasId");

                    b.HasIndex("TblFederalizacionId");

                    b.HasIndex("TblInventariosId");

                    b.HasIndex("TblProveedorId");

                    b.HasIndex("TblResguardatariosId");

                    b.ToTable("TblBienesSistemas");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblClaveCabms", b =>
                {
                    b.Property<int>("TblClaveCabmsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("clavecambs")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblClaveCabmsId");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblClaveCambs");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblClaveSaica", b =>
                {
                    b.Property<int>("TblClaveSaicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("clavesaica")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblClaveSaicaId");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblClaveSaica");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblConfPerfil", b =>
                {
                    b.Property<int?>("IdPermisoid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdRolid")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasIndex("IdPermisoid");

                    b.HasIndex("IdRolid");

                    b.ToTable("TblConfPerfil");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblContratoBien", b =>
                {
                    b.Property<int>("TblContratoBienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("contratobien")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblContratoBienId");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblContratoBien");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblFacturas", b =>
                {
                    b.Property<int>("TblFacturasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<double>("IVA")
                        .HasColumnType("double precision");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<double>("costoTotal")
                        .HasColumnType("double precision");

                    b.Property<int>("costounitario")
                        .HasColumnType("integer");

                    b.Property<string>("factura")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<double>("subtotal")
                        .HasColumnType("double precision");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblFacturasId");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblFacturas");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblFederalizacion", b =>
                {
                    b.Property<int>("TblFederalizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("federalizacion")
                        .HasColumnType("text");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblFederalizacionId");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblFederalizacion");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblInstrumentalMedico", b =>
                {
                    b.Property<int>("TblInstrumentalMedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatEstadoDelBienId")
                        .HasColumnType("integer");

                    b.Property<int>("CatGarantiaId")
                        .HasColumnType("integer");

                    b.Property<int>("CatPisosId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoEntradaId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoPartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("TblAreaServicioId")
                        .HasColumnType("integer");

                    b.Property<int>("TblClaveCabmsId")
                        .HasColumnType("integer");

                    b.Property<int>("TblClaveSaicaId")
                        .HasColumnType("integer");

                    b.Property<int>("TblContratoBienId")
                        .HasColumnType("integer");

                    b.Property<int>("TblFacturasId")
                        .HasColumnType("integer");

                    b.Property<int>("TblFederalizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("TblInventariosId")
                        .HasColumnType("integer");

                    b.Property<int>("TblProveedorId")
                        .HasColumnType("integer");

                    b.Property<int>("TblResguardatariosId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("serie")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblInstrumentalMedicoId");

                    b.HasIndex("CatEstadoDelBienId");

                    b.HasIndex("CatGarantiaId");

                    b.HasIndex("CatPisosId");

                    b.HasIndex("CatTipoDeBienId");

                    b.HasIndex("CatTipoEntradaId");

                    b.HasIndex("CatTipoPartidaId");

                    b.HasIndex("TblAreaServicioId");

                    b.HasIndex("TblClaveCabmsId");

                    b.HasIndex("TblClaveSaicaId");

                    b.HasIndex("TblContratoBienId");

                    b.HasIndex("TblFacturasId");

                    b.HasIndex("TblFederalizacionId");

                    b.HasIndex("TblInventariosId");

                    b.HasIndex("TblProveedorId");

                    b.HasIndex("TblResguardatariosId");

                    b.ToTable("TblInstrumentalMedico");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblInventarios", b =>
                {
                    b.Property<int>("TblInventariosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroInventario")
                        .HasColumnType("text");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblInventariosId");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblInventarios");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblProveedor", b =>
                {
                    b.Property<int>("TblProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("proveedor")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblProveedorId");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblProveedor");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblResguardatarios", b =>
                {
                    b.Property<int>("TblResguardatariosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatEstatusId")
                        .HasColumnType("integer");

                    b.Property<int>("CatSexoId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoContratoId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTurnoId")
                        .HasColumnType("integer");

                    b.Property<string>("RFC")
                        .HasColumnType("text");

                    b.Property<int>("TblAreaServicioId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("apellidoDos")
                        .HasColumnType("text");

                    b.Property<string>("apellidoUno")
                        .HasColumnType("text");

                    b.Property<string>("cargo")
                        .HasColumnType("text");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .HasColumnType("text");

                    b.Property<string>("numeroempleado")
                        .HasColumnType("text");

                    b.Property<string>("plaza")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblResguardatariosId");

                    b.HasIndex("CatEstatusId");

                    b.HasIndex("CatSexoId");

                    b.HasIndex("CatTipoContratoId");

                    b.HasIndex("CatTurnoId");

                    b.HasIndex("TblAreaServicioId");

                    b.ToTable("TblResguardatarios");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblSalidaBienEquMedico", b =>
                {
                    b.Property<int>("TblSalidaBienEquMedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoSalidaId")
                        .HasColumnType("integer");

                    b.Property<int>("CatUnidadDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("TblBienesEquMedicoId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblSalidaBienEquMedicoId");

                    b.HasIndex("CatTipoDeBienId");

                    b.HasIndex("CatTipoSalidaId");

                    b.HasIndex("CatUnidadDestinoId");

                    b.HasIndex("TblBienesEquMedicoId");

                    b.ToTable("TblSalidaBien");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblSalidaBienInstrumentalMedico", b =>
                {
                    b.Property<int>("TblSalidaBienInstrumentalMedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoSalidaId")
                        .HasColumnType("integer");

                    b.Property<int>("CatUnidadDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("TblInstrumentalMedicoId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblSalidaBienInstrumentalMedicoId");

                    b.HasIndex("CatTipoDeBienId");

                    b.HasIndex("CatTipoSalidaId");

                    b.HasIndex("CatUnidadDestinoId");

                    b.HasIndex("TblInstrumentalMedicoId");

                    b.ToTable("tblSalidaBienInstrumentalMedico");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblSalidaBienMobiliario", b =>
                {
                    b.Property<int>("TblSalidaBienMobiliarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoSalidaId")
                        .HasColumnType("integer");

                    b.Property<int>("CatUnidadDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("TblBienesId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblSalidaBienMobiliarioId");

                    b.HasIndex("CatTipoDeBienId");

                    b.HasIndex("CatTipoSalidaId");

                    b.HasIndex("CatUnidadDestinoId");

                    b.HasIndex("TblBienesId");

                    b.ToTable("tblSalidaBienMobiliario");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblSalidaBienSistemas", b =>
                {
                    b.Property<int>("TblSalidaBienSistemasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoSalidaId")
                        .HasColumnType("integer");

                    b.Property<int>("CatUnidadDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("TblBienesSistemasId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblSalidaBienSistemasId");

                    b.HasIndex("CatTipoDeBienId");

                    b.HasIndex("CatTipoSalidaId");

                    b.HasIndex("CatUnidadDestinoId");

                    b.HasIndex("TblBienesSistemasId");

                    b.ToTable("tblSalidaBienSistema");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CatEstatusId")
                        .HasColumnType("integer");

                    b.Property<int>("CatSexoId")
                        .HasColumnType("integer");

                    b.Property<int>("CatTipoContratoId")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTurnoId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("RFC")
                        .HasColumnType("text");

                    b.Property<int>("TblAreaServicioId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("catRolid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("idTok")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("numeroempleado")
                        .HasColumnType("text");

                    b.Property<string>("plaza")
                        .HasColumnType("text");

                    b.Property<int>("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("CatEstatusId");

                    b.HasIndex("CatSexoId");

                    b.HasIndex("CatTipoContratoId");

                    b.HasIndex("CatTurnoId");

                    b.HasIndex("TblAreaServicioId");

                    b.HasIndex("catRolid");

                    b.ToTable("CtrlUsuarios");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblAreaServicio", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatArea", null)
                        .WithMany("tblAreaServicios")
                        .HasForeignKey("CatAreaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatServicio", null)
                        .WithMany("tblAreaServicios")
                        .HasForeignKey("CatServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienes", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatEstadoDelBien", null)
                        .WithMany("tblBienes")
                        .HasForeignKey("CatEstadoDelBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatGarantia", null)
                        .WithMany("tblBienes")
                        .HasForeignKey("CatGarantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatPisos", null)
                        .WithMany("tblBienes")
                        .HasForeignKey("CatPisosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("tblBienes")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoEntrada", null)
                        .WithMany("tblBienes")
                        .HasForeignKey("CatTipoEntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoPartida", null)
                        .WithMany("tblBienes")
                        .HasForeignKey("CatTipoPartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", null)
                        .WithMany("tblBienes")
                        .HasForeignKey("TblAreaServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblClaveCabms", null)
                        .WithMany("tblBienes")
                        .HasForeignKey("TblClaveCabmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblClaveSaica", null)
                        .WithMany("tblBienes")
                        .HasForeignKey("TblClaveSaicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblContratoBien", null)
                        .WithMany("tblBienes")
                        .HasForeignKey("TblContratoBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblFacturas", null)
                        .WithMany("tblBienes")
                        .HasForeignKey("TblFacturasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblFederalizacion", null)
                        .WithMany("TblBienes")
                        .HasForeignKey("TblFederalizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblInventarios", null)
                        .WithMany("tblBienes")
                        .HasForeignKey("TblInventariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblProveedor", null)
                        .WithMany("tblBienes")
                        .HasForeignKey("TblProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblResguardatarios", null)
                        .WithMany("tblBienes")
                        .HasForeignKey("TblResguardatariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienesEquMedico", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatEstadoDelBien", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("CatEstadoDelBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatGarantia", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("CatGarantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatPisos", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("CatPisosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoEntrada", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("CatTipoEntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoPartida", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("CatTipoPartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("TblAreaServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblClaveCabms", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("TblClaveCabmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblClaveSaica", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("TblClaveSaicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblContratoBien", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("TblContratoBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblFacturas", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("TblFacturasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblFederalizacion", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("TblFederalizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblInventarios", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("TblInventariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblProveedor", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("TblProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblResguardatarios", null)
                        .WithMany("tblBienesEquMedico")
                        .HasForeignKey("TblResguardatariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblBienesSistemas", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatEstadoDelBien", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("CatEstadoDelBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatGarantia", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("CatGarantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatPisos", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("CatPisosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoEntrada", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("CatTipoEntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoPartida", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("CatTipoPartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("TblAreaServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblClaveCabms", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("TblClaveCabmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblClaveSaica", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("TblClaveSaicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblContratoBien", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("TblContratoBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblFacturas", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("TblFacturasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblFederalizacion", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("TblFederalizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblInventarios", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("TblInventariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblProveedor", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("TblProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblResguardatarios", null)
                        .WithMany("tblBienesSistemas")
                        .HasForeignKey("TblResguardatariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblClaveCabms", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("tblClaveCabms")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblClaveSaica", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("tblClaveSaica")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblConfPerfil", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatPermiso", "IdPermiso")
                        .WithMany()
                        .HasForeignKey("IdPermisoid");

                    b.HasOne("SICOBIM_B.Entities.CatRol", "IdRol")
                        .WithMany()
                        .HasForeignKey("IdRolid");
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblContratoBien", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("tblContratoBien")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblFacturas", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("tblFacturas")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblFederalizacion", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("tblFederalizacion")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblInstrumentalMedico", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatEstadoDelBien", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("CatEstadoDelBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatGarantia", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("CatGarantiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatPisos", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("CatPisosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoEntrada", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("CatTipoEntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoPartida", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("CatTipoPartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("TblAreaServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblClaveCabms", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("TblClaveCabmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblClaveSaica", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("TblClaveSaicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblContratoBien", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("TblContratoBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblFacturas", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("TblFacturasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblFederalizacion", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("TblFederalizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblInventarios", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("TblInventariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblProveedor", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("TblProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblResguardatarios", null)
                        .WithMany("tblInstrumentalMedico")
                        .HasForeignKey("TblResguardatariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblInventarios", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("tblInventarios")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblProveedor", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("tblProveedor")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblResguardatarios", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatEstatus", null)
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("CatEstatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatSexo", null)
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("CatSexoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoContrato", null)
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("CatTipoContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTurno", null)
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("CatTurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", null)
                        .WithMany("tblResguardatarios")
                        .HasForeignKey("TblAreaServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblSalidaBienEquMedico", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("tblSalidaBienEquMedico")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoSalida", null)
                        .WithMany("tblSalidaBienEquMedico")
                        .HasForeignKey("CatTipoSalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatUnidadDestino", null)
                        .WithMany("tblsalidaBienEquMedico")
                        .HasForeignKey("CatUnidadDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblBienesEquMedico", null)
                        .WithMany("tblSalidaBien")
                        .HasForeignKey("TblBienesEquMedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblSalidaBienInstrumentalMedico", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("TblSalidaBienInstrumentalMedico")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoSalida", null)
                        .WithMany("TblSalidaBienInstrumentalMedico")
                        .HasForeignKey("CatTipoSalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatUnidadDestino", null)
                        .WithMany("TblSalidaBienInstrumentalMedico")
                        .HasForeignKey("CatUnidadDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblInstrumentalMedico", null)
                        .WithMany("TblSalidaBienInstrumentalMedico")
                        .HasForeignKey("TblInstrumentalMedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblSalidaBienMobiliario", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("TblSalidaBienMobiliario")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoSalida", null)
                        .WithMany("TblSalidaBienMobiliario")
                        .HasForeignKey("CatTipoSalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatUnidadDestino", null)
                        .WithMany("TblSalidaBienMobiliario")
                        .HasForeignKey("CatUnidadDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblBienes", null)
                        .WithMany("TblSalidaBienMobiliario")
                        .HasForeignKey("TblBienesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.TblSalidaBienSistemas", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatTipoDeBien", null)
                        .WithMany("TblSalidaBienSistema")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoSalida", null)
                        .WithMany("TblSalidaBienSistema")
                        .HasForeignKey("CatTipoSalidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatUnidadDestino", null)
                        .WithMany("TblSalidaBienSistema")
                        .HasForeignKey("CatUnidadDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.TblBienesSistemas", null)
                        .WithMany("TblSalidaBienSistemas")
                        .HasForeignKey("TblBienesSistemasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.Entities.User", b =>
                {
                    b.HasOne("SICOBIM_B.Entities.CatEstatus", null)
                        .WithMany("users")
                        .HasForeignKey("CatEstatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatSexo", null)
                        .WithMany("users")
                        .HasForeignKey("CatSexoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTipoContrato", null)
                        .WithMany("users")
                        .HasForeignKey("CatTipoContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatTurno", null)
                        .WithMany("users")
                        .HasForeignKey("CatTurnoId");

                    b.HasOne("SICOBIM_B.Entities.TblAreaServicio", null)
                        .WithMany("users")
                        .HasForeignKey("TblAreaServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SICOBIM_B.Entities.CatRol", "catRol")
                        .WithMany("user")
                        .HasForeignKey("catRolid");

                    b.OwnsMany("SICOBIM_B.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<DateTime>("Created")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("text");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("text");

                            b1.Property<string>("Token")
                                .HasColumnType("text");

                            b1.Property<int>("Userid")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("Userid");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner()
                                .HasForeignKey("Userid");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
