// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SICOBIM_B;

namespace SICOBIM_B.Migrations
{
    [DbContext(typeof(sicobimContext))]
    [Migration("20210109022425_tb6")]
    partial class tb6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SICOBIM_B.CatArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Area")
                        .HasColumnName("area")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdusuarioMod")
                        .HasColumnName("idusuarioMod")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioAlta")
                        .HasColumnName("usuarioAlta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatArea");
                });

            modelBuilder.Entity("SICOBIM_B.CatEstadoDelBien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatEstadoDelBien");
                });

            modelBuilder.Entity("SICOBIM_B.CatEstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estatus")
                        .HasColumnName("estatus")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatEstatus");
                });

            modelBuilder.Entity("SICOBIM_B.CatGarantia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("AñosGarantia")
                        .HasColumnName("añosGarantia")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatGarantia");
                });

            modelBuilder.Entity("SICOBIM_B.CatPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("Permiso")
                        .HasColumnName("permiso")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatPermiso");
                });

            modelBuilder.Entity("SICOBIM_B.CatPiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("Piso")
                        .HasColumnName("piso")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatPiso");
                });

            modelBuilder.Entity("SICOBIM_B.CatRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("IdusuarioMod")
                        .HasColumnName("idusuarioMod")
                        .HasColumnType("integer");

                    b.Property<string>("Rol")
                        .HasColumnName("rol")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CatRol");
                });

            modelBuilder.Entity("SICOBIM_B.CatServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdusuarioMod")
                        .HasColumnName("idusuarioMod")
                        .HasColumnType("integer");

                    b.Property<string>("Servicio")
                        .HasColumnName("servicio")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioAlta")
                        .HasColumnName("usuarioAlta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatServicio");
                });

            modelBuilder.Entity("SICOBIM_B.CatSexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("Sexo")
                        .HasColumnName("sexo")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatSexo");
                });

            modelBuilder.Entity("SICOBIM_B.CatTipoContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Contrato")
                        .HasColumnName("contrato")
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatTipoContrato");
                });

            modelBuilder.Entity("SICOBIM_B.CatTipoDeBien", b =>
                {
                    b.Property<int>("CatTipoDeBienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("TipodeBien")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("CatTipoDeBienId");

                    b.ToTable("CatTipoDeBien");
                });

            modelBuilder.Entity("SICOBIM_B.CatTipoEntrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("Tipoentrada")
                        .HasColumnName("tipoentrada")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatTipoEntrada");
                });

            modelBuilder.Entity("SICOBIM_B.CatTipoPartida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("Partidapresupestual")
                        .HasColumnName("partidapresupestual")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatTipoPartida");
                });

            modelBuilder.Entity("SICOBIM_B.CatTipoSalida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("Tiposalida")
                        .HasColumnName("tiposalida")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatTipoSalida");
                });

            modelBuilder.Entity("SICOBIM_B.CatTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("Turno")
                        .HasColumnName("turno")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatTurno");
                });

            modelBuilder.Entity("SICOBIM_B.CatUnidadDestino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Destino")
                        .HasColumnName("destino")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("IdusuarioMod")
                        .HasColumnName("idusuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatUnidadDestino");
                });

            modelBuilder.Entity("SICOBIM_B.CtrlUsuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cargo")
                        .HasColumnName("cargo")
                        .HasColumnType("text");

                    b.Property<int?>("CatEstatusid")
                        .HasColumnName("catEstatusid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatRolid")
                        .HasColumnName("catRolid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatSexoid")
                        .HasColumnName("catSexoid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoContratoid")
                        .HasColumnName("catTipoContratoid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTurnoid")
                        .HasColumnName("catTurnoid")
                        .HasColumnType("integer");

                    b.Property<int?>("Catareaid")
                        .HasColumnName("catAreaid")
                        .HasColumnType("integer");

                    b.Property<int?>("Catservicioid")
                        .HasColumnName("catServicioid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAlta")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("'0001-01-01 00:00:00'::timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("'0001-01-01 00:00:00'::timestamp without time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int>("IdTok")
                        .HasColumnName("idTok")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Numeroempleado")
                        .HasColumnName("numeroempleado")
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("Plaza")
                        .HasColumnName("plaza")
                        .HasColumnType("text");

                    b.Property<string>("Rfc")
                        .HasColumnName("RFC")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatEstatusid");

                    b.HasIndex("CatRolid");

                    b.HasIndex("CatSexoid");

                    b.HasIndex("CatTipoContratoid");

                    b.HasIndex("CatTurnoid");

                    b.HasIndex("Catareaid");

                    b.HasIndex("Catservicioid");

                    b.ToTable("CtrlUsuarios");
                });

            modelBuilder.Entity("SICOBIM_B.TblBienesEquMedico", b =>
                {
                    b.Property<int>("TblBienesEquMedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Cantidad")
                        .HasColumnName("cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("CatEstadoDelBienid")
                        .HasColumnName("catEstadoDelBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatGarantiaid")
                        .HasColumnName("catGarantiaid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatPisosid")
                        .HasColumnName("catPisosid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoDeBienid")
                        .HasColumnName("catTipoDeBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoEntradaid")
                        .HasColumnName("catTipoEntradaid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoPartidaid")
                        .HasColumnName("catTipoPartidaid")
                        .HasColumnType("integer");

                    b.Property<int?>("Catareaid")
                        .HasColumnName("catAreaid")
                        .HasColumnType("integer");

                    b.Property<int?>("Catservicioid")
                        .HasColumnName("catServicioid")
                        .HasColumnType("integer");

                    b.Property<double>("Costounitario")
                        .HasColumnName("costounitario")
                        .HasColumnType("double precision");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdClaveCabmsid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdClaveSaicaid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdContratoBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFacturasid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFederalizacionid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdInventarioid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProveedorid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdResguardatariosid")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .HasColumnName("marca")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnName("modelo")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnName("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Serie")
                        .HasColumnName("serie")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblBienesEquMedicoId");

                    b.HasIndex("CatEstadoDelBienid");

                    b.HasIndex("CatGarantiaid");

                    b.HasIndex("CatPisosid");

                    b.HasIndex("CatTipoDeBienid");

                    b.HasIndex("CatTipoEntradaid");

                    b.HasIndex("CatTipoPartidaid");

                    b.HasIndex("Catareaid");

                    b.HasIndex("Catservicioid");

                    b.HasIndex("IdClaveCabmsid");

                    b.HasIndex("IdClaveSaicaid");

                    b.HasIndex("IdContratoBienid");

                    b.HasIndex("IdFacturasid");

                    b.HasIndex("IdFederalizacionid");

                    b.HasIndex("IdInventarioid");

                    b.HasIndex("IdProveedorid");

                    b.HasIndex("IdResguardatariosid");

                    b.ToTable("TblBienesEquMedico");
                });

            modelBuilder.Entity("SICOBIM_B.TblBienesMuebles", b =>
                {
                    b.Property<int>("TblBienesMueblesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Cantidad")
                        .HasColumnName("cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("CatEstadoDelBienid")
                        .HasColumnName("catEstadoDelBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatGarantiaid")
                        .HasColumnName("catGarantiaid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatPisosid")
                        .HasColumnName("catPisosid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoDeBienid")
                        .HasColumnName("catTipoDeBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoEntradaid")
                        .HasColumnName("catTipoEntradaid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoPartidaid")
                        .HasColumnName("catTipoPartidaid")
                        .HasColumnType("integer");

                    b.Property<int?>("Catareaid")
                        .HasColumnName("catAreaid")
                        .HasColumnType("integer");

                    b.Property<int?>("Catservicioid")
                        .HasColumnName("catServicioid")
                        .HasColumnType("integer");

                    b.Property<double>("Costounitario")
                        .HasColumnName("costounitario")
                        .HasColumnType("double precision");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdClaveCabmsid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdClaveSaicaid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdContratoBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFacturasid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFederalizacionid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdInventarioid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProveedorid")
                        .HasColumnName("IdProveedorid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdResguardatariosid")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .HasColumnName("marca")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnName("modelo")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnName("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Serie")
                        .HasColumnName("serie")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblBienesMueblesId");

                    b.HasIndex("CatEstadoDelBienid");

                    b.HasIndex("CatGarantiaid");

                    b.HasIndex("CatPisosid");

                    b.HasIndex("CatTipoDeBienid");

                    b.HasIndex("CatTipoEntradaid");

                    b.HasIndex("CatTipoPartidaid");

                    b.HasIndex("Catareaid");

                    b.HasIndex("Catservicioid");

                    b.HasIndex("IdClaveCabmsid");

                    b.HasIndex("IdClaveSaicaid");

                    b.HasIndex("IdContratoBienid");

                    b.HasIndex("IdFacturasid");

                    b.HasIndex("IdFederalizacionid");

                    b.HasIndex("IdInventarioid");

                    b.HasIndex("IdProveedorid");

                    b.HasIndex("IdResguardatariosid");

                    b.ToTable("TblBienesMuebles");
                });

            modelBuilder.Entity("SICOBIM_B.TblBienesSistemas", b =>
                {
                    b.Property<int>("TblBienesSistemasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Cantidad")
                        .HasColumnName("cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("CatEstadoDelBienid")
                        .HasColumnName("catEstadoDelBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatGarantiaid")
                        .HasColumnName("catGarantiaid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatPisosid")
                        .HasColumnName("catPisosid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoDeBienid")
                        .HasColumnName("catTipoDeBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoEntradaid")
                        .HasColumnName("catTipoEntradaid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoPartidaid")
                        .HasColumnName("catTipoPartidaid")
                        .HasColumnType("integer");

                    b.Property<int?>("Catareaid")
                        .HasColumnName("catAreaid")
                        .HasColumnType("integer");

                    b.Property<int?>("Catservicioid")
                        .HasColumnName("catServicioid")
                        .HasColumnType("integer");

                    b.Property<double>("Costounitario")
                        .HasColumnName("costounitario")
                        .HasColumnType("double precision");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdClaveCabmsid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdClaveSaicaid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdContratoBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFacturasid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFederalizacionid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdInventarioid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProveedorid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdResguardatariosid")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .HasColumnName("marca")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnName("modelo")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnName("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Serie")
                        .HasColumnName("serie")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblBienesSistemasId");

                    b.HasIndex("CatEstadoDelBienid");

                    b.HasIndex("CatGarantiaid");

                    b.HasIndex("CatPisosid");

                    b.HasIndex("CatTipoDeBienid");

                    b.HasIndex("CatTipoEntradaid");

                    b.HasIndex("CatTipoPartidaid");

                    b.HasIndex("Catareaid");

                    b.HasIndex("Catservicioid");

                    b.HasIndex("IdClaveCabmsid");

                    b.HasIndex("IdClaveSaicaid");

                    b.HasIndex("IdContratoBienid");

                    b.HasIndex("IdFacturasid");

                    b.HasIndex("IdFederalizacionid");

                    b.HasIndex("IdInventarioid");

                    b.HasIndex("IdProveedorid");

                    b.HasIndex("IdResguardatariosid");

                    b.ToTable("TblBienesSistemas");
                });

            modelBuilder.Entity("SICOBIM_B.TblClaveCabms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<string>("Clavecambs")
                        .HasColumnName("clavecambs")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblClaveCambs");
                });

            modelBuilder.Entity("SICOBIM_B.TblClaveSaica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<string>("Clavesaica")
                        .HasColumnName("clavesaica")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblClaveSaica");
                });

            modelBuilder.Entity("SICOBIM_B.TblConfPerfil", b =>
                {
                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdPermisoid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdRolid")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasIndex("IdPermisoid");

                    b.HasIndex("IdRolid");

                    b.ToTable("TblConfPerfil");
                });

            modelBuilder.Entity("SICOBIM_B.TblContratoBien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<string>("Contratobien")
                        .HasColumnName("contratobien")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblContratoBien");
                });

            modelBuilder.Entity("SICOBIM_B.TblFacturas", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<double>("CostoTotal")
                        .HasColumnName("costoTotal")
                        .HasColumnType("double precision");

                    b.Property<string>("Factura")
                        .HasColumnName("factura")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<double>("Iva")
                        .HasColumnName("IVA")
                        .HasColumnType("double precision");

                    b.Property<double>("Subtotal")
                        .HasColumnName("subtotal")
                        .HasColumnType("double precision");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("IdFactura");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblFacturas");
                });

            modelBuilder.Entity("SICOBIM_B.TblFederalizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Federalizacion")
                        .HasColumnName("federalizacion")
                        .HasColumnType("text");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblFederalizacion");
                });

            modelBuilder.Entity("SICOBIM_B.TblInstrumentalMedico", b =>
                {
                    b.Property<int>("TblInstrumentalMedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<int>("Cantidad")
                        .HasColumnName("cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("CatEstadoDelBienid")
                        .HasColumnName("catEstadoDelBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatGarantiaid")
                        .HasColumnName("catGarantiaid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatPisosid")
                        .HasColumnName("catPisosid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoDeBienid")
                        .HasColumnName("catTipoDeBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoEntradaid")
                        .HasColumnName("catTipoEntradaid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoPartidaid")
                        .HasColumnName("catTipoPartidaid")
                        .HasColumnType("integer");

                    b.Property<int?>("Catareaid")
                        .HasColumnName("catAreaid")
                        .HasColumnType("integer");

                    b.Property<int?>("Catservicioid")
                        .HasColumnName("catServicioid")
                        .HasColumnType("integer");

                    b.Property<double>("Costounitario")
                        .HasColumnName("costounitario")
                        .HasColumnType("double precision");

                    b.Property<string>("Descripcion")
                        .HasColumnName("descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdClaveCambsid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdClaveSaicaid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdContratoBienid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFacturasid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdFederalizacionid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdInventarioid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProveedorid")
                        .HasColumnType("integer");

                    b.Property<int?>("IdResguardatariosid")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .HasColumnName("marca")
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .HasColumnName("modelo")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnName("observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Serie")
                        .HasColumnName("serie")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("TblInstrumentalMedicoId");

                    b.HasIndex("CatEstadoDelBienid");

                    b.HasIndex("CatGarantiaid");

                    b.HasIndex("CatPisosid");

                    b.HasIndex("CatTipoDeBienid");

                    b.HasIndex("CatTipoEntradaid");

                    b.HasIndex("CatTipoPartidaid");

                    b.HasIndex("Catareaid");

                    b.HasIndex("Catservicioid");

                    b.HasIndex("IdClaveCambsid");

                    b.HasIndex("IdClaveSaicaid");

                    b.HasIndex("IdContratoBienid");

                    b.HasIndex("IdFacturasid");

                    b.HasIndex("IdFederalizacionid");

                    b.HasIndex("IdInventarioid");

                    b.HasIndex("IdProveedorid");

                    b.HasIndex("IdResguardatariosid");

                    b.ToTable("TblInstrumentalMedico");
                });

            modelBuilder.Entity("SICOBIM_B.TblInventarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroInventario")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblInventarios");
                });

            modelBuilder.Entity("SICOBIM_B.TblProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("Proveedor")
                        .HasColumnName("proveedor")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatTipoDeBienId");

                    b.ToTable("TblProveedor");
                });

            modelBuilder.Entity("SICOBIM_B.TblResguardatarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ApellidoDos")
                        .HasColumnName("apellidoDos")
                        .HasColumnType("text");

                    b.Property<string>("ApellidoUno")
                        .HasColumnName("apellidoUno")
                        .HasColumnType("text");

                    b.Property<string>("Cargo")
                        .HasColumnName("cargo")
                        .HasColumnType("text");

                    b.Property<int?>("CatEstatusid")
                        .HasColumnName("catEstatusid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatServicioid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatSexoid")
                        .HasColumnName("catSexoid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoContratoid")
                        .HasColumnName("catTipoContratoid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTurnoid")
                        .HasColumnName("catTurnoid")
                        .HasColumnType("integer");

                    b.Property<int?>("Catareaid")
                        .HasColumnType("integer");

                    b.Property<int?>("Catservicioid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("IdServicioId")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnName("nombre")
                        .HasColumnType("text");

                    b.Property<string>("Numeroempleado")
                        .HasColumnName("numeroempleado")
                        .HasColumnType("text");

                    b.Property<string>("Plaza")
                        .HasColumnName("plaza")
                        .HasColumnType("text");

                    b.Property<string>("Rfc")
                        .HasColumnName("RFC")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatEstatusid");

                    b.HasIndex("CatServicioid");

                    b.HasIndex("CatSexoid");

                    b.HasIndex("CatTipoContratoid");

                    b.HasIndex("CatTurnoid");

                    b.HasIndex("Catareaid");

                    b.HasIndex("IdServicioId");

                    b.ToTable("TblResguardatarios");
                });

            modelBuilder.Entity("SICOBIM_B.TblSalidas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Activo")
                        .HasColumnName("activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CatTipoDeBienId")
                        .HasColumnType("integer");

                    b.Property<int?>("CatTipoSalidaid")
                        .HasColumnName("catTipoSalidaid")
                        .HasColumnType("integer");

                    b.Property<int?>("CatUnidadDestinoid")
                        .HasColumnName("catUnidadDestinoid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnName("fechaAlta")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaMod")
                        .HasColumnName("fechaMod")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IdBien")
                        .HasColumnName("IdBien")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuarioAlta")
                        .HasColumnName("idUsuarioAlta")
                        .HasColumnType("integer");

                    b.Property<int?>("TblBienesEquMedicoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TblBienesMueblesId")
                        .HasColumnType("integer");

                    b.Property<int?>("TblBienesSistemasId")
                        .HasColumnType("integer");

                    b.Property<int?>("TblInstrumentalMedicoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioMod")
                        .HasColumnName("usuarioMod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatTipoDeBienId");

                    b.HasIndex("CatTipoSalidaid");

                    b.HasIndex("CatUnidadDestinoid");

                    b.HasIndex("TblBienesEquMedicoId");

                    b.HasIndex("TblBienesMueblesId");

                    b.HasIndex("TblBienesSistemasId");

                    b.HasIndex("TblInstrumentalMedicoId");

                    b.ToTable("TblSalidas");
                });

            modelBuilder.Entity("SICOBIM_B.CtrlUsuarios", b =>
                {
                    b.HasOne("SICOBIM_B.CatEstatus", "CatEstatus")
                        .WithMany("CtrlUsuarios")
                        .HasForeignKey("CatEstatusid");

                    b.HasOne("SICOBIM_B.CatRol", "CatRol")
                        .WithMany("CtrlUsuarios")
                        .HasForeignKey("CatRolid");

                    b.HasOne("SICOBIM_B.CatSexo", "CatSexo")
                        .WithMany("CtrlUsuarios")
                        .HasForeignKey("CatSexoid");

                    b.HasOne("SICOBIM_B.CatTipoContrato", "CatTipoContrato")
                        .WithMany("CtrlUsuarios")
                        .HasForeignKey("CatTipoContratoid");

                    b.HasOne("SICOBIM_B.CatTurno", "CatTurno")
                        .WithMany("CtrlUsuarios")
                        .HasForeignKey("CatTurnoid");

                    b.HasOne("SICOBIM_B.CatArea", "IdArea")
                        .WithMany("CtrlUsuarios")
                        .HasForeignKey("Catareaid");

                    b.HasOne("SICOBIM_B.CatServicio", "IdServicio")
                        .WithMany("CtrlUsuarios")
                        .HasForeignKey("Catservicioid");

                    b.OwnsMany("SICOBIM_B.RefreshToken", "RefreshToken", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                            b1.Property<DateTime>("Created")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("CreatedByIp")
                                .HasColumnType("text");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("RevokedByIp")
                                .HasColumnType("text");

                            b1.Property<string>("Token")
                                .HasColumnType("text");

                            b1.Property<int>("Userid")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("Userid");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner("User")
                                .HasForeignKey("Userid");
                        });
                });

            modelBuilder.Entity("SICOBIM_B.TblBienesEquMedico", b =>
                {
                    b.HasOne("SICOBIM_B.CatEstadoDelBien", "CatEstadoDelBien")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("CatEstadoDelBienid");

                    b.HasOne("SICOBIM_B.CatGarantia", "CatGarantia")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("CatGarantiaid");

                    b.HasOne("SICOBIM_B.CatPiso", "CatPisos")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("CatPisosid");

                    b.HasOne("SICOBIM_B.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("CatTipoDeBienid")
                        .HasConstraintName("FK_TblBienesEquMedico_CatTipoDeBien_catTipoDeBienesCatTipoDeBi~");

                    b.HasOne("SICOBIM_B.CatTipoEntrada", "CatTipoEntrada")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("CatTipoEntradaid");

                    b.HasOne("SICOBIM_B.CatTipoPartida", "CatTipoPartida")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("CatTipoPartidaid");

                    b.HasOne("SICOBIM_B.CatArea", "IdArea")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("Catareaid");

                    b.HasOne("SICOBIM_B.CatServicio", "IdServicio")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("Catservicioid");

                    b.HasOne("SICOBIM_B.TblClaveCabms", "IdClaveCabms")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("IdClaveCabmsid");

                    b.HasOne("SICOBIM_B.TblClaveSaica", "IdClaveSaica")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("IdClaveSaicaid");

                    b.HasOne("SICOBIM_B.TblContratoBien", "IdContratoBien")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("IdContratoBienid");

                    b.HasOne("SICOBIM_B.TblFacturas", "IdFactura")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("IdFacturasid");

                    b.HasOne("SICOBIM_B.TblFederalizacion", "IdFederalizacion")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("IdFederalizacionid");

                    b.HasOne("SICOBIM_B.TblInventarios", "IdInventario")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("IdInventarioid");

                    b.HasOne("SICOBIM_B.TblProveedor", "IdProveedor")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("IdProveedorid");

                    b.HasOne("SICOBIM_B.TblResguardatarios", "IdResguardatarios")
                        .WithMany("TblBienesEquMedico")
                        .HasForeignKey("IdResguardatariosid");
                });

            modelBuilder.Entity("SICOBIM_B.TblBienesMuebles", b =>
                {
                    b.HasOne("SICOBIM_B.CatEstadoDelBien", "CatEstadoDelBien")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("CatEstadoDelBienid");

                    b.HasOne("SICOBIM_B.CatGarantia", "CatGarantia")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("CatGarantiaid");

                    b.HasOne("SICOBIM_B.CatPiso", "CatPisos")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("CatPisosid");

                    b.HasOne("SICOBIM_B.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("CatTipoDeBienid")
                        .HasConstraintName("FK_TblBienesMuebles_CatTipoDeBien_catTipoDeBienesCatTipoDeBien~");

                    b.HasOne("SICOBIM_B.CatTipoEntrada", "CatTipoEntrada")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("CatTipoEntradaid");

                    b.HasOne("SICOBIM_B.CatTipoPartida", "CatTipoPartida")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("CatTipoPartidaid");

                    b.HasOne("SICOBIM_B.CatArea", "IdArea")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("Catareaid");

                    b.HasOne("SICOBIM_B.CatServicio", "IdServicio")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("Catservicioid");

                    b.HasOne("SICOBIM_B.TblClaveCabms", "IdClaveCabms")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("IdClaveCabmsid");

                    b.HasOne("SICOBIM_B.TblClaveSaica", "IdClaveSaica")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("IdClaveSaicaid");

                    b.HasOne("SICOBIM_B.TblContratoBien", "IdContratoBien")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("IdContratoBienid");

                    b.HasOne("SICOBIM_B.TblFacturas", "IdFactura")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("IdFacturasid");

                    b.HasOne("SICOBIM_B.TblFederalizacion", "IdFederalizacion")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("IdFederalizacionid");

                    b.HasOne("SICOBIM_B.TblInventarios", "IdInventario")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("IdInventarioid");

                    b.HasOne("SICOBIM_B.TblProveedor", "IdProveedor")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("IdProveedorid");

                    b.HasOne("SICOBIM_B.TblResguardatarios", "IdResguardatarios")
                        .WithMany("TblBienesMuebles")
                        .HasForeignKey("IdResguardatariosid");
                });

            modelBuilder.Entity("SICOBIM_B.TblBienesSistemas", b =>
                {
                    b.HasOne("SICOBIM_B.CatEstadoDelBien", "CatEstadoDelBien")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("CatEstadoDelBienid");

                    b.HasOne("SICOBIM_B.CatGarantia", "CatGarantia")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("CatGarantiaid");

                    b.HasOne("SICOBIM_B.CatPiso", "CatPisos")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("CatPisosid");

                    b.HasOne("SICOBIM_B.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("CatTipoDeBienid")
                        .HasConstraintName("FK_TblBienesSistemas_CatTipoDeBien_catTipoDeBienesCatTipoDeBie~");

                    b.HasOne("SICOBIM_B.CatTipoEntrada", "CatTipoEntrada")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("CatTipoEntradaid");

                    b.HasOne("SICOBIM_B.CatTipoPartida", "CatTipoPartida")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("CatTipoPartidaid");

                    b.HasOne("SICOBIM_B.CatArea", "IdArea")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("Catareaid");

                    b.HasOne("SICOBIM_B.CatServicio", "IdServicio")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("Catservicioid");

                    b.HasOne("SICOBIM_B.TblClaveCabms", "IdClaveCabms")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("IdClaveCabmsid");

                    b.HasOne("SICOBIM_B.TblClaveSaica", "IdClaveSaica")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("IdClaveSaicaid");

                    b.HasOne("SICOBIM_B.TblContratoBien", "IdContratoBien")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("IdContratoBienid");

                    b.HasOne("SICOBIM_B.TblFacturas", "IdFactura")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("IdFacturasid");

                    b.HasOne("SICOBIM_B.TblFederalizacion", "IdFederalizacion")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("IdFederalizacionid");

                    b.HasOne("SICOBIM_B.TblInventarios", "IdInventario")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("IdInventarioid");

                    b.HasOne("SICOBIM_B.TblProveedor", "IdProveedor")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("IdProveedorid");

                    b.HasOne("SICOBIM_B.TblResguardatarios", "IdResguardatarios")
                        .WithMany("TblBienesSistemas")
                        .HasForeignKey("IdResguardatariosid");
                });

            modelBuilder.Entity("SICOBIM_B.TblClaveCabms", b =>
                {
                    b.HasOne("SICOBIM_B.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany("TblClaveCambs")
                        .HasForeignKey("CatTipoDeBienId");
                });

            modelBuilder.Entity("SICOBIM_B.TblClaveSaica", b =>
                {
                    b.HasOne("SICOBIM_B.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany("TblClaveSaica")
                        .HasForeignKey("CatTipoDeBienId");
                });

            modelBuilder.Entity("SICOBIM_B.TblConfPerfil", b =>
                {
                    b.HasOne("SICOBIM_B.CatPermiso", "IdPermiso")
                        .WithMany()
                        .HasForeignKey("IdPermisoid");

                    b.HasOne("SICOBIM_B.CatRol", "IdRol")
                        .WithMany()
                        .HasForeignKey("IdRolid");
                });

            modelBuilder.Entity("SICOBIM_B.TblContratoBien", b =>
                {
                    b.HasOne("SICOBIM_B.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany("TblContratoBien")
                        .HasForeignKey("CatTipoDeBienId");
                });

            modelBuilder.Entity("SICOBIM_B.TblFacturas", b =>
                {
                    b.HasOne("SICOBIM_B.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany("TblFacturas")
                        .HasForeignKey("CatTipoDeBienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SICOBIM_B.TblFederalizacion", b =>
                {
                    b.HasOne("SICOBIM_B.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany("TblFederalizacion")
                        .HasForeignKey("CatTipoDeBienId");
                });

            modelBuilder.Entity("SICOBIM_B.TblInstrumentalMedico", b =>
                {
                    b.HasOne("SICOBIM_B.CatEstadoDelBien", "CatEstadoDelBien")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("CatEstadoDelBienid");

                    b.HasOne("SICOBIM_B.CatGarantia", "CatGarantia")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("CatGarantiaid");

                    b.HasOne("SICOBIM_B.CatPiso", "CatPisos")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("CatPisosid");

                    b.HasOne("SICOBIM_B.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("CatTipoDeBienid")
                        .HasConstraintName("FK_TblInstrumentalMedico_CatTipoDeBien_catTipoDeBienesCatTipoD~");

                    b.HasOne("SICOBIM_B.CatTipoEntrada", "CatTipoEntrada")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("CatTipoEntradaid");

                    b.HasOne("SICOBIM_B.CatTipoPartida", "CatTipoPartida")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("CatTipoPartidaid");

                    b.HasOne("SICOBIM_B.CatArea", "IdArea")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("Catareaid");

                    b.HasOne("SICOBIM_B.CatServicio", "IdServicio")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("Catservicioid");

                    b.HasOne("SICOBIM_B.TblClaveCabms", "IdClaveCambs")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("IdClaveCambsid");

                    b.HasOne("SICOBIM_B.TblClaveSaica", "IdClaveSaica")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("IdClaveSaicaid");

                    b.HasOne("SICOBIM_B.TblContratoBien", "IdContratoBien")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("IdContratoBienid");

                    b.HasOne("SICOBIM_B.TblFacturas", "IdFactura")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("IdFacturasid");

                    b.HasOne("SICOBIM_B.TblFederalizacion", "IdFederalizacion")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("IdFederalizacionid");

                    b.HasOne("SICOBIM_B.TblInventarios", "IdInventario")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("IdInventarioid");

                    b.HasOne("SICOBIM_B.TblProveedor", "IdProveedor")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("IdProveedorid");

                    b.HasOne("SICOBIM_B.TblResguardatarios", "IdResguardatarios")
                        .WithMany("TblInstrumentalMedico")
                        .HasForeignKey("IdResguardatariosid");
                });

            modelBuilder.Entity("SICOBIM_B.TblInventarios", b =>
                {
                    b.HasOne("SICOBIM_B.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany("TblInventarios")
                        .HasForeignKey("CatTipoDeBienId");
                });

            modelBuilder.Entity("SICOBIM_B.TblProveedor", b =>
                {
                    b.HasOne("SICOBIM_B.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany("TblProveedor")
                        .HasForeignKey("CatTipoDeBienId");
                });

            modelBuilder.Entity("SICOBIM_B.TblResguardatarios", b =>
                {
                    b.HasOne("SICOBIM_B.CatEstatus", "CatEstatus")
                        .WithMany("TblResguardatarios")
                        .HasForeignKey("CatEstatusid");

                    b.HasOne("SICOBIM_B.CatServicio", "CatServicio")
                        .WithMany("TblResguardatarios")
                        .HasForeignKey("CatServicioid");

                    b.HasOne("SICOBIM_B.CatSexo", "CatSexo")
                        .WithMany("TblResguardatarios")
                        .HasForeignKey("CatSexoid");

                    b.HasOne("SICOBIM_B.CatTipoContrato", "CatTipoContrato")
                        .WithMany("TblResguardatarios")
                        .HasForeignKey("CatTipoContratoid");

                    b.HasOne("SICOBIM_B.CatTurno", "CatTurno")
                        .WithMany("TblResguardatarios")
                        .HasForeignKey("CatTurnoid");

                    b.HasOne("SICOBIM_B.CatArea", "IdArea")
                        .WithMany("TblResguardatarios")
                        .HasForeignKey("Catareaid");

                    b.HasOne("SICOBIM_B.CatServicio", "IdServicio")
                        .WithMany()
                        .HasForeignKey("IdServicioId");
                });

            modelBuilder.Entity("SICOBIM_B.TblSalidas", b =>
                {
                    b.HasOne("SICOBIM_B.CatTipoDeBien", "CatTipoDeBien")
                        .WithMany("TblSalidas")
                        .HasForeignKey("CatTipoDeBienId");

                    b.HasOne("SICOBIM_B.CatTipoSalida", "CatTipoSalida")
                        .WithMany("TblSalidas")
                        .HasForeignKey("CatTipoSalidaid");

                    b.HasOne("SICOBIM_B.CatUnidadDestino", "CatUnidadDestino")
                        .WithMany("TblSalidas")
                        .HasForeignKey("CatUnidadDestinoid");

                    b.HasOne("SICOBIM_B.TblBienesEquMedico", null)
                        .WithMany("TblSalidas")
                        .HasForeignKey("TblBienesEquMedicoId");

                    b.HasOne("SICOBIM_B.TblBienesMuebles", null)
                        .WithMany("TblSalidas")
                        .HasForeignKey("TblBienesMueblesId");

                    b.HasOne("SICOBIM_B.TblBienesSistemas", null)
                        .WithMany("TblSalidas")
                        .HasForeignKey("TblBienesSistemasId");

                    b.HasOne("SICOBIM_B.TblInstrumentalMedico", null)
                        .WithMany("TblSalidas")
                        .HasForeignKey("TblInstrumentalMedicoId");
                });
#pragma warning restore 612, 618
        }
    }
}
